char readme[]=
"Program %s\n"
"Author: Ugo Bastolla <ubastolla@cbm.csic.es>\n"
"Centro de Biologia Molecular Severo Ochoa (CSIC-UAM)\n\n"
"The program unfolds a protein constraining the mechanical energy E, moving only the backbone torsion angles. It computes the specific heat dE/dT and derivative of the gyration radius with respect to the control parameter T interpreted as a pseudo-temperature.\n\n"
"The method defines the pseudo free-energy F=E-T*Rg^2, where Rg^2=sum_i m_i |ri|^2/M is the gyration radius and E=sum_ij C_ij f(r_ij)+ K_tors*sum_a (phi_a-phi0_a)^2 is the anharmonic structure-based + repulsion energy function described in Dehouck and Bastolla 2021, Biophys J 120 5343-5354.\n\n"
"For each pseudo-temperature T, the program determines the average conformation that minimizes F allowing only motions of the torsion angles phi_a by solving dF/dphi_a=dF/dr_i dr_i/dphi_a =0 forall a => delta_phi ~ (d^2F/dphi_a dphi_b)^(-1)(dF/dphi_a), analogous to linear response, and it reconstructs the Cartesian coordinates from the modified torsion angles.\n\n"
"The program prints three output files:\n"
"- <pdbid>.unfolding.pdb Coordinates at increasing T (only if RMSD>0.35A)\n"
"- <pdbid>.torsion.dat   Change of each torsion angle at temp T from T=0\n"
"- <pdbid>.unfolding.dat with eight columns:\n"
"1=T 2=RMSD 3=E 4=Rg 5=F=E-TRg^2 6=RMS(force) 7=dE/dT 8=dRg^2/dT\n\n"
"Compile:\n"
">unzip unfold.zip\n"
">make -f make_unfold.make\n\n"
"Executable: unfold\n\n"
"USAGE:\n"
">unfold -pdb <pdbfile> (mandatory)\n"
"        -ch <chain_labels> (default: first chain; ALL= all chains)\n"
"        -kt <parameter K_tors> (default: 0)\n"
"        -nT <number of simulated pseudo-temperatures> (def: 1000)\n"
"        -dT <Increment of pseudo-temperatures> (def: 40)\n"
"        -ann  <Number of steps of simulated annealing> (def: 120)\n"
"        -fact <Factor of simulated annealing> (def. 1.1)\n"
"        -rmsd <RMSD difference for printint PDB> (def: 0.3)\n"
"        -amax <Max angular increment in torsion angles> (def: 0.01)\n"
"        -refold ! Try to compact the protein by penalyzing Rg^2 \n"
"        -h  Print this help and exit\n\n";
